<?php
$form = $this->form;
$fieldset = $form->get('label');

$name = $fieldset->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Label name');

$default_text = $fieldset->get('default_text');
$default_text->setAttribute('class', 'form-control');
$default_text->setAttribute('placeholder', 'Default text');

$submit = $form->get('submit');
$submit->setValue($this->submitLabel);
$submit->setAttribute('class', 'btn btn-primary');

$form->prepare();

echo $this->form()->openTag($form);
?>

<fieldset>
<div class="form-group">
    <?= $this->formLabel($name) ?>
    <?= $this->formElement($name) ?>
    <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($default_text) ?>
    <?= $this->formElement($default_text) ?>
    <?= $this->formElementErrors()->render($default_text, ['class' => 'help-block']) ?>
</div>
</fieldset>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($fieldset->get('id'));
echo $this->form()->closeTag();