-- MySQL Script generated by MySQL Workbench
-- Sun Aug 16 21:16:19 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema horisen_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `horisen_test` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `horisen_test` ;

-- -----------------------------------------------------
-- Table `language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `language` (
  `lang` CHAR(2) CHARACTER SET 'latin1' COLLATE 'latin1_general_ci' NOT NULL DEFAULT 'en',
  `name` VARCHAR(30) NOT NULL DEFAULT '',
  `is_default` ENUM('yes','no') NOT NULL DEFAULT 'no',
  PRIMARY KEY (`lang`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ht_label`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ht_label` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL DEFAULT '',
  `default_text` VARCHAR(1000) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_name` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ht_label_trans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ht_label_trans` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `label_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `language` CHAR(2) CHARACTER SET 'latin1' COLLATE 'latin1_general_ci' NOT NULL DEFAULT 'zx',
  `text` VARCHAR(1000) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_label` (`label_id` ASC, `language` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `language`
-- -----------------------------------------------------
START TRANSACTION;
USE `horisen_test`;
INSERT INTO `language` (`lang`, `name`, `is_default`) VALUES ('en', 'English', 'yes');
INSERT INTO `language` (`lang`, `name`, `is_default`) VALUES ('de', 'Deutsch', 'no');
INSERT INTO `language` (`lang`, `name`, `is_default`) VALUES ('fr', concat('fran', _utf8 x'C3A7', 'ais'), 'no');
INSERT INTO `language` (`lang`, `name`, `is_default`) VALUES ('it', 'italiano', 'no');

COMMIT;

